name: Ping rogergaham.fi

on:
  schedule:
    - cron: "*/15 * * * *" # Every 15 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping website
        run: |
          response=$(curl -Is https://rogergraham.fi | head -n 1)
          echo "Response: $response"
          if ! echo "$response" | grep -q "200"; then
            echo "Website is down!"
            exit 1
          fi
